goaop/parser-reflection

src/ReflectionEngine.php
This is needed to correctly work with parent classes
=> Always injects file name into the class nodes

src/Traits/ReflectionClassLikeTrait.php
When checking class constant has `NULL` as it's value and it's being checked using `ReflectionClass::hasConstant` method then there will be a notice and constant will be returned as non-existent.
This happens, because `array_key_exists` function has different argument order.
Most likely tests doesn't cover this use case. I've found this code in Symfony framework.
P.S.
If tests are needed, then I'm happy to provide them if you'd show me some examples. I'm new to library and therefore need some assistance please.
=> Fixing notice, when using "ReflectionClass::hasConstant" method

tests/ReflectionClassTest.php, tests/Stub/FileWithClasses55.php
While adding tests for `ReflectionClass::hasConstant`, that was fixed in #25 I've also found out, that `ReflectionClass::getConstant` isn't directly tested as well. So I've added tests for it as well.
Related to #25
=> Add tests for "ReflectionClass::hasConstant" and "ReflectionClass::getConstant" methods

src/ReflectionEngine.php
I've decided to clear all parsed files, when limit is reached instead just removing last parsed file. This technique is looking more promising for cases, when you parse several large files upfront and can't lower memory usage, because they can't be removed later.
Closes #18
=> Limit number of cached files (with a setting)

composer.json
When `branch-alias` present in `composer.json` it comes possible to specify version like `^1.1@dev` when requiring the library. This way project using the library will get it's dev dependency, but whoever uses that project would use live dependency instead.
=> Adding "branch-alias" to "composer.json"

src/Instrument/PathResolver.php, src/Locator/ComposerLocator.php, src/ReflectionEngine.php, src/ReflectionFile.php, src/ReflectionFileNamespace.php, tests/Locator/ComposerLocatorTest.php
This PR solves an issue with relative paths from the composer, when filename returned from locator can contain points. 
Thanks to @aik099. Resolves #31
=> Resolve all relative paths to be compatibe with original reflection

src/NodeVisitor/RootNamespaceNormalizer.php, src/ReflectionEngine.php, src/ReflectionFile.php, tests/ReflectionFileTest.php, tests/ReflectionParameterTest.php, tests/Stub/FileWithParameters.php
This PR should enable support of reflecting top-level classes without namespace with class method with default parameters, equals to one of: [true, false, null]
=> Add root namespace normalization, resolves #39

src/Traits/ReflectionClassLikeTrait.php, src/ValueResolver/NodeExpressionResolver.php, tests/Stub/FileWithClasses56.php
This PR introduces support for evaluation of scalar expressions in constants and parameters for PHP>=5.6
=> [NodeResolver] allow parsing of scalar expressions

src/NodeVisitor/RootNamespaceNormalizer.php, src/ReflectionFile.php, tests/ReflectionFileTest.php, tests/Stub/FileWithClasses70.php, tests/Stub/FileWithClasses71.php, tests/Stub/FileWithGlobalNamespace.php
Provides an API for checking the `strict_types` mode in files via `ReflectionFile->isStrictMode()`. This API can be useful for proxy generation to keep the correct execution mode for scalar values.
=> Implement ReflectionFile->isStrictMode check for the strict_types

.travis.yml, composer.json, src/Traits/ReflectionClassLikeTrait.php
This PR should make `newInstance()` method implementation compatible with all modern PHP versions.
See https://3v4l.org/eeVf8 for implementation detail
=> Change the signature of ReflectionClass::newInstance

src/NodeVisitor/RootNamespaceNormalizer.php, src/ReflectionClass.php, src/ReflectionFile.php, src/ReflectionFileNamespace.php, src/ReflectionMethod.php, src/ReflectionParameter.php, src/ReflectionType.php, src/Traits/ReflectionClassLikeTrait.php, src/Traits/ReflectionFunctionLikeTrait.php, src/ValueResolver/NodeExpressionResolver.php, src/bootstrap.php, src/polyfill.php, tests/ReflectionFileNamespaceTest.php, tests/ReflectionFileTest.php, tests/ReflectionTypeTest.php, tests/Stub/FileWithClasses70.php, tests/ValueResolver/NodeExpressionResolverTest.php
This PR addresses most of the issues highlighted by the Scrutinizer code analysis tool this package is already coupled to.
=> Scrutinizer fixes

src/Traits/ReflectionClassLikeTrait.php, src/Traits/ReflectionFunctionLikeTrait.php, tests/AbstractTestCase.php, tests/ReflectionClassTest.php
This is an offshoot of #82. This PR eliminates the `forward_static_call()` calls that should not exist in non-static methods. I expanded the test for `setStaticPropertyValue()` and `getStaticPropertyValue()` to try and produce a bad behavior, and was unable to, so the original code **does** seem to work. The problem is that calling `forward_static_call()` from a non-static method doesn't make any sense. My test confirms, at least for the `setStaticPropertyValue()` and `getStaticPropertyValue()` methods, that both the old and new code **works**.
I did not add any tests for `getClosureThis()` and `getClosureScopeClass()`, as I don't think the current implementation can work with closures since `PhpParser\Node\Expr\Closure` doesn't have a `getName()` method, and should fail when either are …
=> Eliminate nonsencical forward_static_call()s

src/Locator/CallableLocator.php, src/Locator/ComposerLocator.php, src/LocatorInterface.php, src/ReflectionClass.php, src/ReflectionMethod.php, src/ReflectionProperty.php, tests/Locator/CallableLocatorTest.php, tests/Locator/ComposerLocatorTest.php, tests/Stub/Issue44/Locator.php
I found a inconsistent behavior about classname in native \Reflection* and \Go\ParserReflection\Reflection* 
Is it unexpected behavior? The native Reflection* constructors drop the leading slash in the string class name parameter. I made changes in constructors to consist behavior and pass thees tests.  It's ready to push. Also it closes #80.
=> Fix problems with leading '\' in FQCNs

src/ReflectionFileNamespace.php, tests/ReflectionFileNamespaceTest.php, tests/Stub/FileWithNamespaces.php
```php
// file to parse
use SomeClass\WithoutAlias;
use AnotherClass\WithAlias as SomeSuperClass;
// parse the file somewhere else
$result = $reflectionNamespace->getNamespaceAliases();
```
```
$result = [
'SomeClass\WithoutAlias' => 'WithoutAlias'
'AnotherClass\WithAlias' => 'SomeSuperClass'
];
```
```
$result = [
'SomeClass\WithoutAlias' => null
'AnotherClass\WithAlias' => 'SomeSuperClass'
];
```
The result of getNamespaceAliases() was changed in version 2.0 through a change in php-parser v4.
In php-parser v3 you can find this fallback logic for "use"-statements without an "as" (so without an alias): https://github.com/nikic/PHP-Parser/blob/3.x/lib/PhpParser/Builder/Use_.php#L53
The logic was moved in v4 from the builder: https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Buil …
=> getNamespaceAliases() behavior changed in 2.0

composer.json
New patch release should be prepared quickly to have proper `endTokenPos` reporting.
=> Temporary restrict installation of broken php-parser versions

composer.json, tests/AbstractTestCase.php, tests/Locator/CallableLocatorTest.php, tests/Locator/ComposerLocatorTest.php, tests/ReflectionClassConstantTest.php, tests/ReflectionFileNamespaceTest.php, tests/ReflectionFileTest.php, tests/ReflectionFunctionTest.php, tests/ReflectionParameterTest.php, tests/ReflectionTypeTest.php, tests/ValueResolver/NodeExpressionResolverTest.php
- Using the `PHPUnit` `^7.0` version to support the `php-7.1+` versions.
- Using the `PHPUnit\Framework\TestCase` to support `PHPUnit ^7` version.
- The PHPUnit `^7` version about fixture is `protected function setUp(): void`.
- Since `php-7.4` version is released, the `implode` function arguments are `implode($glue, $pieces)` . It should be swapped.
The deprecated message is follows:
`PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters`
The more details about `implode` is available on [official PHP doc](https://www.php.net/manual/en/function.implode.php#refsect1-function.implode-changelog).
=> Improve PHPUnit namespace and some stuffs

src/ReflectionEngine.php
According to https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf.
Should resolve #99 
I could not find any tests for `\Go\ParserReflection\ReflectionEngine::parseClass()`, so I did not add new ones for now. We could figure some out though.
=> [Feature] Make it possible to scan for deprecated types.

.github/workflows/phpunit.yml, composer.json, phpunit.xml.dist, src/ReflectionClassConstant.php, src/ReflectionFunction.php, src/ReflectionMethod.php, src/ReflectionProperty.php, src/ReflectionType.php, src/Traits/ReflectionClassLikeTrait.php, tests/AbstractTestCase.php, tests/ReflectionClassTest.php, tests/ReflectionFunctionTest.php, tests/ReflectionMethodTest.php, tests/ReflectionParameterTest.php, tests/ReflectionTypeTest.php, tests/Stub/FileWithClasses80.php
@lisachenko here the 2nd step 👍 , bump to php 8.0
=> [Step 2 Upgrade] Bump requirement to php 8.0

tests/ReflectionClassTest.php
@lisachenko here the 3rd step 👍 , enable skipped test of `ReflectionClassTest::testGetModifiers()`
=> [Step 3 Upgrade] Enable skipped test: ReflectionClassTest::testGetModifiers()

.github/workflows/phpunit.yml, composer.json, src/ReflectionParameter.php, src/Traits/ReflectionFunctionLikeTrait.php
@lisachenko here the 5th step 👍 , bump to php 8.2
=> [Step 5 Upgrade] Bump requirement to php 8.2

src/ReflectionProperty.php
Using at `goaop/framework`:
***Before**
```
Fatal error: During inheritance of ReflectionProperty: Uncaught ErrorException: Return type of Go\ParserReflection\ReflectionProperty::getValue($object = null) should either be compatible with ReflectionProperty::getValue(?object $object = null): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/samsonasik/www/framework-3/vendor/goaop/parser-reflection/src/ReflectionProperty.php:196
Stack trace:
```
**After**
```
D 126 / 210 ( 60%)
DDDDD...........................................DDDDDDD........ 189 / 210 ( 90%)
.....................                                           210 / 210 (100%)
Time: 00:01.921, Memory: 28.00 MB
```
=> Fix ReflectionProperty::getValue() to use #[\ReturnTypeWillChange]
